# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\"y\n\x0e\x43lientResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.ClientResponse.Status\x12\x10\n\x08leaderID\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\\\n\x06\x43lient\x12(\n\x08SetValue\x12\x0b.SetRequest\x1a\x0f.ClientResponse\x12(\n\x08GetValue\x12\x0b.GetRequest\x1a\x0f.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENTRESPONSE']._serialized_start=16
  _globals['_CLIENTRESPONSE']._serialized_end=137
  _globals['_CLIENTRESPONSE_STATUS']._serialized_start=106
  _globals['_CLIENTRESPONSE_STATUS']._serialized_end=137
  _globals['_SETREQUEST']._serialized_start=139
  _globals['_SETREQUEST']._serialized_end=179
  _globals['_GETREQUEST']._serialized_start=181
  _globals['_GETREQUEST']._serialized_end=221
  _globals['_CLIENT']._serialized_start=223
  _globals['_CLIENT']._serialized_end=315
# @@protoc_insertion_point(module_scope)
