# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"O\n\x0bVoteRequest\x12\x0b\n\x03\x63id\x18\x01 \x01(\x05\x12\r\n\x05\x63Term\x18\x02 \x01(\x05\x12\x12\n\ncLogLength\x18\x03 \x01(\x05\x12\x10\n\x08\x63LogTerm\x18\x04 \x01(\x05\"t\n\x0cVoteResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.VoteResponse.Status\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0e\n\x06nodeID\x18\x03 \x01(\x05\" \n\x06Status\x12\x0c\n\x08SUCCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\"y\n\x0e\x43lientResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.ClientResponse.Status\x12\x10\n\x08leaderID\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"(\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"%\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06update\x18\x02 \x03(\t\"\x82\x01\n\nLogRequest\x12\x10\n\x08leaderID\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x11\n\tprefixLen\x18\x03 \x01(\x05\x12\x12\n\nprefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\x06.Entry\"\x92\x01\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x05\x12\x0e\n\x06nodeID\x18\x03 \x01(\x05\x12-\n\x06status\x18\x04 \x01(\x0e\x32\x1d.AppendEntriesResponse.Status\"\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\xbc\x01\n\x04Raft\x12*\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12(\n\x08SetValue\x12\x0b.SetRequest\x1a\x0f.ClientResponse\x12(\n\x08GetValue\x12\x0b.GetRequest\x1a\x0f.ClientResponse\x12\x34\n\rAppendEntries\x12\x0b.LogRequest\x1a\x16.AppendEntriesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=14
  _globals['_VOTEREQUEST']._serialized_end=93
  _globals['_VOTERESPONSE']._serialized_start=95
  _globals['_VOTERESPONSE']._serialized_end=211
  _globals['_VOTERESPONSE_STATUS']._serialized_start=179
  _globals['_VOTERESPONSE_STATUS']._serialized_end=211
  _globals['_CLIENTRESPONSE']._serialized_start=213
  _globals['_CLIENTRESPONSE']._serialized_end=334
  _globals['_CLIENTRESPONSE_STATUS']._serialized_start=303
  _globals['_CLIENTRESPONSE_STATUS']._serialized_end=334
  _globals['_SETREQUEST']._serialized_start=336
  _globals['_SETREQUEST']._serialized_end=376
  _globals['_GETREQUEST']._serialized_start=378
  _globals['_GETREQUEST']._serialized_end=418
  _globals['_ENTRY']._serialized_start=420
  _globals['_ENTRY']._serialized_end=457
  _globals['_LOGREQUEST']._serialized_start=460
  _globals['_LOGREQUEST']._serialized_end=590
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=593
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=739
  _globals['_APPENDENTRIESRESPONSE_STATUS']._serialized_start=303
  _globals['_APPENDENTRIESRESPONSE_STATUS']._serialized_end=334
  _globals['_RAFT']._serialized_start=742
  _globals['_RAFT']._serialized_end=930
# @@protoc_insertion_point(module_scope)
